<a href="https://colab.research.google.com/github/teshomey/teshomey/blob/main/Introduction_to_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Introduction to Python**

## Basic commands

In [3]:
print("Hello World!")

Hello World!


In [4]:
print("Hello" + " World!")

Hello World!


### Creating a list

In [5]:
x = [1, 2, 3, 4, 5]
print(x)

[1, 2, 3, 4, 5]


In [6]:
y = [6, 7, 8]
print(x+y)

[1, 2, 3, 4, 5, 6, 7, 8]


### NumPy

This package is mainly used for numerical operations. To access numpy, we should have toimport it first.

In [7]:
import numpy as np
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(x + y)

[5 7 9]


Creating matrix is also possible.

In [9]:
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(mat) # note the the closure [] for all elements.

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
mat.ndim

2

In [11]:
mat.dtype

dtype('int64')

In [12]:
mat.shape

(3, 3)

### Methods

In [13]:
x = np.array([1,2,3,4,5])
x.sum()

15

In [14]:
np.sum(x)

15